# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_details', models.CharField(max_length=500)),
                ('product_image', models.CharField(max_length=2000)),
                ('product_price', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
            ],
        ),
    ]
