# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='file_type',
            new_name='gender',
        ),
    ]
