# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0002_auto_20170321_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
