# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0003_auto_20170327_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to=b''),
        ),
    ]
